### PR TITLE
Some corrections

### PR DESCRIPTION
**Pull request by dmtr99**
1. The variable ctl was never set in the methods Pacify and set, use "this.ctl" (try changing the name of the control in the example from ctl to ctl1, then an error will occur)
2. The function dbg is also used in other libraries, to make it more general, I renamed it to dbg_scintilla
3. Changed filepath definition so that the dll files just need to be inside the libraryfolder.

### CODE REVIEW

**Comment by dmtr99** [comment]
Apparently, using this.ctl is also not the correct way to fix the problem...

**Comment by TheArkive** [comment]
> Apparently, using this.ctl is also not the correct way to fix the problem...

Correct, in that case, it needs to just be `this.Length-1` (which is actually not 100% the best solution either, as it only works with UTF-8, but one thing at a time).

Only the sub classes use `this.ctl` in order to maintain a connection between the main class (the scintilla control) and the sub classes that help modifying it's settings and properties.  So the ones in `Get()` are correct as `this.ctl`.

I'm still reviewing a few changes.  Good job, and thanks 😄 just change that first one to `this.Length`

EDIT:

If ya make the previous change (`this.Length`) then I can commit this change.

**Comment by dmtr99** [comment]
updated

**Comment by TheArkive** [comment]
Line 443, `this.ctl.Length` needs to be `this.Length` ... then that should do it.

EDIT:  Oops my bad, i wasn't looking at the proper change.  I see you already did it.

**Pull request merged**
